/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
    extend: {
      colors: {
        "tertiary-container": "#2e2f2c",
        "on-primary": "#ffffff",
        "secondary-container": "#fed3c7",
        "on-surface": "#1b1c1c",
        "primary-fixed": "#cde9db",
        "on-secondary-fixed": "#2c160e",
        "tertiary": "#1a1a18",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed-variant": "#5d4037",
        "primary-container": "#1b332a",
        "inverse-primary": "#b1cdc0",
        "secondary-fixed": "#ffdbd0",
        "primary": "#051e16",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#e7bdb1",
        "primary-fixed-dim": "#b1cdc0",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed": "#1b1c19",
        "inverse-surface": "#303030",
        "surface": "#fcf9f8",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "secondary": "#77574d",
        "on-tertiary-fixed-variant": "#474744",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#795950",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-background": "#1b1c1c",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#072018",
        "outline": "#727975",
        "on-primary-container": "#829c90",
        "on-surface-variant": "#424845",
        "tertiary-fixed-dim": "#c8c6c2",
        "outline-variant": "#c2c8c3",
        "surface-bright": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed": "#e4e2dd",
        "surface-variant": "#e5e2e1",
        "on-tertiary-container": "#979692",
        "surface-tint": "#4b6459",
        "on-primary-fixed-variant": "#334c42"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "unit": "8px",
        "container-max": "1360px"
      },
      fontFamily: {
        "headline-display": ["Playfair Display", "serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "label-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "headline-display": ["clamp(2.5rem, 5vw + 1rem, 4.5rem)", { "lineHeight": "1.08", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "label-lg": ["14px", { "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["clamp(1.5rem, 2.5vw + 0.5rem, 2.25rem)", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["clamp(2rem, 3.5vw + 0.75rem, 3.25rem)", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
